[package]
name = "subc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
pest = "2.1.3"
pest_derive = "2.1.0"

[features]
